const _ = require('lodash');

const array = [1,2,3,4,"one","two","three", 1.2,2.4,3.6,true,false]
const array2 = [1,2,3,3,2]

const lodash_difference = _.difference(array, array2)
const lodash_intersection = _.intersection(array, array2)
const lodash_union = _.union(array, array2)
const lodash_uniq = _.uniq(array)
const lodash_without = _.without(array, 1,2,3,false)
// const lodash_with = _.with(array, 5,6,7,8,9,10)
const lodash_zip = _.zip(array, array2)
const lodash_zipObject = _.zipObject(array, array2)
const lodash_zipWith = _.zipWith(array, array2)
const lodash_at = _.at(array, [0,1])
// const lodash_atRight = _.atRight(array, [0,1])
const lodash_chunk = _.chunk(array, 2)
const lodash_compact = _.compact(array)
const lodash_concat = _.concat(array, array2)
const lodash_differenceBy = _.differenceBy(array, array2, [iterate = _.identity])
const lodash_get = _.get('array[5]')
const lodash_head = _.head(array)
const lodash_filter = _.filter(array, (item) => typeof(item) === "string")
const lodash_find = _.find(array, (item) => typeof(item) === "number")
const lodash_findIndex = _.findIndex(array, (item) => typeof(item) === "number")
const lodash_findLast = _.findLast(array, (item) => typeof(item) === "number")
const lodash_flatten = _.flatten(array)
const lodash_includes = _.includes(array, 1)
const lodash_intersectionBy = _.intersectionBy(array, array2)


console.log("lodash_difference",lodash_difference)
console.log("lodash_intersection",lodash_intersection)
console.log("lodash_union",lodash_union)
console.log("lodash_uniq",lodash_uniq)
console.log("lodash_without",lodash_without)
// console.log(lodash_with)
console.log("lodash_zip",lodash_zip)
console.log("lodash_zipObject",lodash_zipObject)
console.log("lodash_zipWith",lodash_zipWith)
console.log("lodash_at",lodash_at)
// console.log("lodash_atRight",lodash_atRight)
console.log("lodash_chunk",lodash_chunk)
console.log("lodash_compact",lodash_compact)
console.log("lodash_concat",lodash_concat)
console.log("lodash_differenceBy",lodash_differenceBy)
console.log("lodash_get",lodash_get)
console.log("lodash_head",lodash_head)
console.log("lodash_filter",lodash_filter)
console.log("lodash_find",lodash_find)
console.log("lodash_findIndex",lodash_findIndex)
console.log("lodash_findLast",lodash_findLast)
console.log("lodash_flatten",lodash_flatten)
console.log("lodash_includes",lodash_includes)
console.log("lodash_intersectionBy",lodash_intersectionBy)

